(() => {
"use strict";
const KEY_NAME="jarvis_key";
const MEMORY_NAME="jarvis_memory";
const MODELS=["gemini-2.5-flash","gemini-2.5-flash-lite"];
const SYSTEM_INSTRUCTION=`You are J.A.R.V.I.S, a helpful personal AI assistant. Follow the user's requested language. If the user says Telugu, reply in Telugu Unicode. If the user asks English, reply in English. If the user uses Telugu-English or Roman Telugu, reply in simple Telugu-English/Roman Telugu as appropriate. Never change the requested language unless the user asks. Keep answers clear and practical. Do not read or discuss formatting markers merely because they appear around text; treat them as content only when the user explicitly asks about them.`;
let API_KEY="";
let MEMORY=loadMemory();
const $=id=>document.getElementById(id);
let chat,input,micBtn,clearBtn,camBtn,imgInput,sendBtn,keyModal,keyInput,saveKeyBtn,cancelKeyBtn,keyError;
function loadMemory(){try{const x=JSON.parse(localStorage.getItem(MEMORY_NAME)||"[]");return Array.isArray(x)?x.filter(m=>m&&m.text&&((m.role==="user")||(m.role==="model"))):[]}catch{return[]}}
function saveMemory(){localStorage.setItem(MEMORY_NAME,JSON.stringify(MEMORY.slice(-100)));}
function openKeyModal(){if(!keyModal)return; keyModal.hidden=false; keyInput.value=""; keyError.textContent=""; setTimeout(()=>keyInput.focus(),50);}
function closeKeyModal(){if(keyModal)keyModal.hidden=true;}
function setKey(){const k=keyInput.value.trim();if(!k){keyError.textContent="Please enter an API key.";return false;} API_KEY=k;localStorage.setItem(KEY_NAME,k);closeKeyModal();return true;}
function ensureKey(){API_KEY=localStorage.getItem(KEY_NAME)||"";if(!API_KEY)openKeyModal();return !!API_KEY;}
function add(text,type){if(!chat)return;const div=document.createElement("div");div.className="msg "+type;div.textContent=text;chat.appendChild(div);chat.scrollTop=chat.scrollHeight;return div;}
function showMemory(){chat.innerHTML="";MEMORY.forEach(m=>add((m.role==="user"?"YOU: ":"J.A.R.V.I.S: ")+m.text,m.role==="user"?"user":"ai"));}
function cleanSpeech(text){return String(text||"").replace(/```[\s\S]*?```/g," code omitted ").replace(/https?:\/\/\S+/gi," link omitted ").replace(/www\.\S+/gi," link omitted ").replace(/[\*#_`~|{}\[\]<>]/g," ").replace(/\s+/g," ").trim();}
function speak(text){if(!("speechSynthesis" in window))return;speechSynthesis.cancel();const clean=cleanSpeech(text);if(!clean)return;const u=new SpeechSynthesisUtterance(clean);u.rate=1.03;u.pitch=.85;const v=speechSynthesis.getVoices().find(x=>/^en-IN/i.test(x.lang))||speechSynthesis.getVoices().find(x=>/^en/i.test(x.lang));if(v)u.voice=v;speechSynthesis.speak(u);}
function buildContents(extra){const contents=MEMORY.slice(-20).map(m=>({role:m.role,parts:[{text:m.text}]}));contents.push({role:"user",parts:[{text:extra}]});return contents;}
async function gemini(contents){if(!ensureKey())throw new Error("Gemini API key is required.");let last="Unknown API error";for(const model of MODELS){try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(API_KEY)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({system_instruction:{parts:[{text:SYSTEM_INSTRUCTION}]},contents,generationConfig:{temperature:.7,maxOutputTokens:2048}})});const d=await r.json();if(!r.ok||d.error){last=d?.error?.message||`HTTP ${r.status}`;if(r.status===400||r.status===401||r.status===403){break}continue}const text=d?.candidates?.[0]?.content?.parts?.map(p=>p.text||"").join("").trim();if(text)return text;last="Gemini returned no text."}catch(e){last=e.message||String(e)}}throw new Error(last);}
async function askGemini(prompt,alreadyShown=false){if(!ensureKey())return;const thinking=add("J.A.R.V.I.S: Thinking...","ai");try{const reply=await gemini(buildContents(prompt));MEMORY.push({role:"user",text:prompt},{role:"model",text:reply});saveMemory();thinking.textContent="J.A.R.V.I.S: "+reply;speak(reply)}catch(e){thinking.textContent="J.A.R.V.I.S: ERROR - "+e.message}}
async function askVision(base64,mime,question){if(!ensureKey())return;const box=add("J.A.R.V.I.S: Analyzing image...","ai");try{let last="";for(const model of MODELS){const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(API_KEY)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({system_instruction:{parts:[{text:SYSTEM_INSTRUCTION+" For image questions, describe only what can reasonably be observed. Do not invent details."}]},contents:[{role:"user",parts:[{text:question},{inline_data:{mime_type:mime,data:base64}}]}],generationConfig:{temperature:.4,maxOutputTokens:1024}})});const d=await r.json();if(!r.ok||d.error){last=d?.error?.message||`HTTP ${r.status}`;if(r.status===400||r.status===401||r.status===403)break;continue}const reply=d?.candidates?.[0]?.content?.parts?.map(p=>p.text||"").join("").trim();if(reply){box.textContent="J.A.R.V.I.S: "+reply;speak(reply);return}}throw new Error(last||"Image analysis failed.")}catch(e){box.textContent="J.A.R.V.I.S: ERROR - "+e.message}}
function setup(){chat=$("chat");input=$("msg");micBtn=$("mic-btn");clearBtn=$("clear-btn");camBtn=$("cam-btn");imgInput=$("img-input");sendBtn=$("send");keyModal=$("key-modal");keyInput=$("api-key-input");saveKeyBtn=$("save-key");cancelKeyBtn=$("cancel-key");keyError=$("key-error");showMemory();ensureKey();saveKeyBtn?.addEventListener("click",setKey);cancelKeyBtn?.addEventListener("click",()=>{if(!API_KEY)closeKeyModal()});sendBtn?.addEventListener("click",()=>{const t=input.value.trim();if(!t)return;input.value="";add("YOU: "+t,"user");askGemini(t)});input?.addEventListener("keydown",e=>{if(e.key==="Enter")sendBtn?.click()});clearBtn?.addEventListener("click",()=>{if(confirm("Clear J.A.R.V.I.S memory?")){MEMORY=[];saveMemory();showMemory();add("SYSTEM: Memory cleared.","ai")}});camBtn?.addEventListener("click",()=>imgInput?.click());imgInput?.addEventListener("change",()=>{const file=imgInput.files?.[0];if(!file)return;const q=input.value.trim()||"What do you see? Describe briefly.";input.value="";add("YOU: [IMAGE] "+q,"user");const reader=new FileReader();reader.onload=()=>askVision(String(reader.result).split(",")[1],file.type,q);reader.readAsDataURL(file);imgInput.value=""});setupMic();}
function setupMic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR||!micBtn)return;const r=new SR();r.lang="en-IN";r.interimResults=false;r.maxAlternatives=1;micBtn.addEventListener("click",()=>{try{r.start();micBtn.textContent="LISTENING..."}catch{}});r.onresult=e=>{const t=e.results?.[0]?.[0]?.transcript?.trim();if(t){add("YOU: "+t,"user");askGemini(t)}};r.onerror=e=>add("SYSTEM: Microphone error - "+e.error,"ai");r.onend=()=>micBtn.textContent="🎙️"}
document.addEventListener("DOMContentLoaded",setup);
})();